config/routes.rb
Rails.application.routes.draw do
  resources :situations

  resources :materials

  resources :downloads

  resources :characters

  get 'soon', to:'comingsoon#index'
  get 'home', to:'wicker#index'

  # if Rails.env.production?
  #   root 'comingsoon#index'
  # else
  #   root 'wicker#index'
  # end
  root 'wicker#index'
end

app/models/character.rb
class Character < ActiveRecord::Base
end

app/models/download.rb
class Download < ActiveRecord::Base
  belongs_to :material
end

app/models/material.rb
class Material < ActiveRecord::Base
  has_many :downloads, dependent: :destroy
end

app/models/situation.rb
class Situation < ActiveRecord::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  http_basic_authenticate_with name: "gabe", password: "poopington"
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  def index
    @characters = Character.all
  end

  def show
  end

  def new
    @character = Character.new
  end

  def edit
  end

  def create
    @character = Character.new(character_params)
    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_character
      @character = Character.find(params[:id])
    end

    def character_params
      params.require(:character).permit(:name, :age, :bio, :occupation, :species, :status, :animatedimg, :portraitimg)
    end
end

app/controllers/comingsoon_controller.rb
class ComingsoonController < ApplicationController

  def index

  end

end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  http_basic_authenticate_with name: "gabe", password: "poopington"
  before_action :set_download, only: [:show, :edit, :update, :destroy]

  def index
    @downloads = Download.all
  end

  def show
  end


  def new
    @download = Download.new
  end

  def edit
  end

  def create
    @download = Download.new(download_params)

    respond_to do |format|
      if @download.save
        format.html { redirect_to @download, notice: 'Download was successfully created.' }
        format.json { render :show, status: :created, location: @download }
      else
        format.html { render :new }
        format.json { render json: @download.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @download.update(download_params)
        format.html { redirect_to @download, notice: 'Download was successfully updated.' }
        format.json { render :show, status: :ok, location: @download }
      else
        format.html { render :edit }
        format.json { render json: @download.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @download.destroy
    respond_to do |format|
      format.html { redirect_to downloads_url, notice: 'Download was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_download
      @download = Download.find(params[:id])
    end

    def download_params
      params[:download]
      params.require(:download).permit(:file, :material_id, :description, :link)

    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  http_basic_authenticate_with name: "gabe", password: "poopington"
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  def index
    @materials = Material.all
  end


  def show
  end


  def new
    @material = Material.new
  end


  def edit
  end

  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_material
      @material = Material.find(params[:id])
    end

    def material_params
      params.require(:material).permit(:name, :description)
    end
end

app/controllers/situations_controller.rb
class SituationsController < ApplicationController
  http_basic_authenticate_with name: "gabe", password: "poopington"
  before_action :set_situation, only: [:show, :edit, :update, :destroy]

  def index
    @situations = Situation.all
  end


  def show
  end


  def new
    @situation = Situation.new
  end


  def edit
  end

  def create
    @situation = Situation.new(situation_params)

    respond_to do |format|
      if @situation.save
        format.html { redirect_to @situation, notice: 'Situation was successfully created.' }
        format.json { render :show, status: :created, location: @situation }
      else
        format.html { render :new }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @situation.update(situation_params)
        format.html { redirect_to @situation, notice: 'Situation was successfully updated.' }
        format.json { render :show, status: :ok, location: @situation }
      else
        format.html { render :edit }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @situation.destroy
    respond_to do |format|
      format.html { redirect_to situations_url, notice: 'Situation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_situation
      @situation = Situation.find(params[:id])
    end

    def situation_params
      params.require(:situation).permit(:name, :description, :situationimg, :situationthumbnail, :headingcolor)
    end
end

app/controllers/wicker_controller.rb
class WickerController < ApplicationController

  def index
    @characters = Character.all
    @situations = Situation.all
    @downloads = Download.all
    @materials = Material.all
  end

end

app/views/characters/_form.html.haml
= form_for @character do |f|
  - if @character.errors.any?
    #error_explanation
      %h2= "#{pluralize(@character.errors.count, "error")} prohibited this character from being saved:"
      %ul
        - @character.errors.full_messages.each do |msg|
          %li= msg
  %p{:class => 'ui form'}
    = f.label :name
    = f.text_field :name
    = f.label :age
    = f.text_field :age
    = f.label :species
    = f.text_field :species
    = f.label :occupation
    = f.text_field :occupation
    = f.label :status
    = f.text_field :status
    = f.label :animatedimg
    = f.text_field :animatedimg
    = f.label :bio
    = f.text_area :bio, :class => 'tinymce', :rows => 20, :cols => 120
    .ui.grid
      .right.floated.right.aligned.three.wide.column
        = f.submit 'Save', class: 'ui basic button'
=tinymce

app/views/characters/edit.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'characters' }
.ui.grid
  .twelve.wide.column.centered
    %h1
      Editing
      =@character.name
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Show', @character, class:'ui basic button green'
    = link_to 'Back', characters_path, class:'ui basic button'

app/views/characters/index.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'characters' }
.ui.grid
  .twelve.wide.column.centered
    %h1 Wicker Wonder Characters
    .ui.divider
    %table{:class=> 'ui table'}
      %thead
        %tr
          %th
            Character Name
          %th
            Show
          %th
            Edit
          %th
            Delete

      %tbody
        - @characters.each do |character|
          %tr
            %td= character.name
            %td= link_to 'Show', character
            %td{:class=>'warning'}= link_to 'Edit', edit_character_path(character)
            %td{:class=>'error'}= link_to 'Destroy', character, :method => :delete, :data => { :confirm => 'Are you sure?' }
    .ui.divider
    = link_to 'New Character', new_character_path, class: 'ui orange basic button'

app/views/characters/new.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'characters' }
.ui.grid
  .twelve.wide.column.centered
    %h1 New character
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Back', characters_path, class: 'ui green basic button'

app/views/characters/show.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'characters' }
%p#notice= notice
.wckr.character.name
  =@character.name
.ui.divider
.ui.grid
  .ui.three.wide.column
    .wckr.character.pairing
      %span Age:
      %span
        =@character.age
    .wckr.character.pairing
      %span Species:
      %span
        =@character.species
    .wckr.character.pairing
      %span Occupation:
      %span
        =@character.occupation
    .wckr.character.pairing
      %span Status:
      %span
        =@character.status
  .ui.five.wide.column
    .wckr.character.pairing
      %span Bio:
      .wckr.character.biography
        =@character.bio.html_safe
  .ui.three.wide.column
    .wckr.character.pairing
      %span Animated Image:
      %img{:src=> image_path('characters/'+@character.animatedimg)}
.ui.divider
= link_to 'Edit', edit_character_path(@character), class: 'ui red basic button'
= link_to 'Back', characters_path, class: 'ui green basic button'

app/views/comingsoon/index.html.haml
.coming.soon
  .wicker
    .title-hold
      .title
        Coming Soon

app/views/downloads/_form.html.haml
= form_for @download do |f|
  - if @download.errors.any?
    #error_explanation
      %h2= "#{pluralize(@download.errors.count, "error")} prohibited this download from being saved:"
      %ul
        - @download.errors.full_messages.each do |msg|
          %li= msg
  %p{:class => 'ui form'}
    = f.label :file
    = f.text_field :file
    = f.label :link
    = f.text_field :link
    = f.label :material_id
    = f.select(:material_id, Material.all.collect{|m| [m.name, m.id]})
    = f.label :description
    = f.text_area :description, :class => 'tinymce', :rows => 10, :cols => 120
    .ui.grid
      .right.floated.right.aligned.three.wide.column
        = f.submit 'Save',class: 'ui basic button'
=tinymce

app/views/downloads/edit.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'downloads' }
.ui.grid
  .twelve.wide.column.centered
    %h1
      Editing
      =@download.file
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Show', @download, class:'ui basic button green'
    = link_to 'Back', downloads_path, class:'ui basic button'

app/views/downloads/index.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'downloads' }
.ui.grid
  .twelve.wide.column.centered
    %h1 Wicker Wonder Downloads
    .ui.divider
    %table{:class=> 'ui table'}
      %thead
        %tr
          %th
            Download
          %th
            Show
          %th
            Edit
          %th
            Delete
      %tbody
        - @downloads.each do |d|
          %tr
            %td= d.file
            %td= link_to 'Show', d
            %td{:class=>'warning'}= link_to 'Edit', edit_download_path(d)
            %td{:class=>'error'}= link_to 'Destroy', d, :method => :delete, :data => { :confirm => 'Are you sure?' }
    .ui.divider
    = link_to 'New Download', new_download_path, class: 'ui orange basic button'

app/views/downloads/new.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'downloads' }
.ui.grid
  .twelve.wide.column.centered
    %h1 New downloads
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Back', downloads_path, class: 'ui green basic button'

app/views/downloads/show.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'downloads' }
%p#notice= notice
- m = Material.find(@download.material_id)
%strong
  For:
%span
  =m.name
%div
  %a{:href=>@download.link}
    =@download.file
= link_to 'Edit', edit_download_path(@download), class: 'ui red basic button'
= link_to 'Back', downloads_path, class: 'ui green basic button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Wicker Wonder
    %script{ :type => 'text/javascript', :src => '//use.typekit.net/jql8arq.js'}
    %script{ :type => 'text/javascript'} try{Typekit.load();}catch(e){}
    %script{ :src => '//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js'}
    %script{ :src => '//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js'}
    %script{ :src => '//cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/plugins/ScrollToPlugin.min.js'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/materials/_form.html.haml
= form_for @material do |f|
  - if @material.errors.any?
    #error_explanation
      %h2= "#{pluralize(@material.errors.count, "error")} prohibited this material from being saved:"
      %ul
        - @material.errors.full_messages.each do |msg|
          %li= msg
  %p{:class => 'ui form'}
    = f.label :name
    = f.text_field :name
    = f.label :description
    = f.text_area :description, :class => 'tinymce', :rows => 20, :cols => 120
    .ui.grid
      .right.floated.right.aligned.three.wide.column
        = f.submit 'Save', class: 'ui basic button'
=tinymce

app/views/materials/edit.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'materials' }
.ui.grid
  .twelve.wide.column.centered
    %h1
      Editing
      =@material.name
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Show', @material, class:'ui basic button green'
    = link_to 'Back', materials_path, class:'ui basic button'

app/views/materials/index.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'materials' }
.ui.grid
  .twelve.wide.column.centered
    %h1 Wicker Wonder Materials
    .ui.divider
    %table{:class=> 'ui table'}
      %thead
        %tr
          %th
            Material
          %th
            Show
          %th
            Edit
          %th
            Delete

      %tbody
        - @materials.each do |material|
          %tr
            %td= material.name
            %td= link_to 'Show', material
            %td{:class=>'warning'}= link_to 'Edit', edit_material_path(material)
            %td{:class=>'error'}= link_to 'Destroy', material, :method => :delete, :data => { :confirm => 'Are you sure?' }
    .ui.divider
    = link_to 'New Material', new_material_path, class: 'ui orange basic button'

app/views/materials/new.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'materials' }
.ui.grid
  .twelve.wide.column.centered
    %h1 New material
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Back', materials_path, class: 'ui green basic button'

app/views/materials/show.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'materials' }
%p#notice= notice
.ui.divider
.ui.grid
  .ui.three.wide.column
    .ui.row
      %strong Name:
      %span
        =@material.name
    .ui.row
      %strong Description:
      %div
        =@material.description.html_safe
.ui.divider
= link_to 'Edit', edit_material_path(@material), class: 'ui red basic button'
= link_to 'Back', materials_path, class: 'ui green basic button'

app/views/situations/_form.html.haml
= form_for @situation do |f|
  - if @situation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@situation.errors.count, "error")} prohibited this situation from being saved:"
      %ul
        - @situation.errors.full_messages.each do |msg|
          %li= msg
  %p{:class => 'ui form'}
    = f.label :name
    = f.text_field :name
    = f.label :situationimg
    = f.text_field :situationimg
    = f.label :headingcolor
    = f.radio_button :headingcolor, 'light', :checked=> true
    = label :headingcolor, 'Light'
    = f.radio_button :headingcolor, 'dark'
    = label :headingcolor, 'Dark'
    = f.radio_button :headingcolor, 'yellow'
    = label :headingcolor, 'Yellow'
    = f.radio_button :headingcolor, 'blue'
    = label :headingcolor, 'Blue'
    %br
    = f.label :description
    = f.text_area :description, :class => 'tinymce', :rows => 40, :cols => 120
    .ui.grid
      .right.floated.right.aligned.three.wide.column
        = f.submit 'Save', class: 'ui basic button'
=tinymce

app/views/situations/edit.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'situations' }
.ui.grid
  .twelve.wide.column.centered
    %h1
      Editing
      =@situation.name
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Show', @situation, class:'ui basic button green'
    = link_to 'Back', situations_path, class:'ui basic button'

app/views/situations/index.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'situations' }
.ui.grid
  .twelve.wide.column.centered
    %h1 Wicker Wonder Situations
    .ui.divider
    %table{:class=> 'ui table'}
      %thead
        %tr
          %th
            Situation
          %th
            Show
          %th
            Edit
          %th
            Delete

      %tbody
        - @situations.each do |situation|
          %tr
            %td= situation.name
            %td= link_to 'Show', situation
            %td{:class=>'warning'}= link_to 'Edit', edit_situation_path(situation)
            %td{:class=>'error'}= link_to 'Destroy', situation, :method => :delete, :data => { :confirm => 'Are you sure?' }
    .ui.divider
    = link_to 'New Situation', new_situation_path, class: 'ui orange basic button'

app/views/situations/new.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'situations' }
.ui.grid
  .twelve.wide.column.centered
    %h1 New Situations
    .ui.divider
    = render 'form'
    .ui.divider
    = link_to 'Back', situations_path, class: 'ui green basic button'

app/views/situations/show.html.haml
= render :partial => '/components/adminnav', :locals => { :current => 'situations' }
%p#notice= notice
.ui.divider
.ui.grid
  .ui.three.wide.column
    .ui.row
      %div
        %strong Name:
        %span
          =@situation.name
      %div
        %strong Color:
        %span
          =@situation.headingcolor
  .ui.five.wide.column
    .ui.row
      %strong Description:
      .div
        =@situation.description.html_safe
  .ui.three.wide.column
    %strong Situation Image:
    %img{:src=> image_path('situations/'+@situation.situationimg)}
.ui.divider
= link_to 'Edit', edit_situation_path(@situation), class: 'ui red basic button'
= link_to 'Back', situations_path, class: 'ui green basic button'

app/views/wicker/index.html.haml
.ui.left.vertical.inverted.labeled.icon.sidebar.menu{:id => 'sidenav'}
  %a{:class=>'item', :href=>'#wicker_welcome', :id => 'wicker_welcome_nav'}
    Home
  %a{:class=>'item', :href=>'#wicker_characters', :id => 'wicker_characters_nav'}
    Meet the Characters
  %a{:class=>'item', :href=>'#wicker_situations', :id => 'wicker_situations_nav'}
    Wicker's World
  %a{:class=>'item', :href=>'#wicker_info', :id=>'wicker_info_nav'}
    Contact
  %a{:class=>'item', :href=>'#wicker_materials', :id=>'wicker_materials_nav'}
    Download Materials
.pusher
  .ui.black.right.icon.button{:id=>'trigger'}
    %i{:class=>'content icon'}
  = render :partial => 'components/welcome'
  = render :partial => 'components/characters', :locals => {:characters => @characters}
  = render :partial => 'components/situations', :locals => {:situations => @situations}
  = render :partial => 'components/closer'
  = render :partial => 'components/materials', :locals => {:downloads => @downloads, :materials => @materials}